# Generated by Django 4.2.19 on 2025-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, default='food_item_pics/food_default.png', null=True, upload_to='food_item_pics/'),
        ),
    ]
