# Generated by Django 4.2.19 on 2025-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_totalamount_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='itemss',
            field=models.ManyToManyField(to='orders.cartitem'),
        ),
    ]
