# Generated by Django 4.2.19 on 2025-03-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_items_order_itemss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemss',
            new_name='items',
        ),
    ]
