# Generated by Django 4.2.19 on 2025-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_items'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'is_vegan', 'is_vegetarian'), name='unique_food_item'),
        ),
    ]
